"""A

Revision ID: 1e621053a3aa
Revises: cc7acf7394c2
Create Date: 2020-05-05 16:22:42.950644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e621053a3aa'
down_revision = 'cc7acf7394c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_users_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'users_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_users_id_fkey', 'comments', 'users', ['users_id'], ['id'])
    # ### end Alembic commands ###
