"""Initial Migration

Revision ID: 716406e19c30
Revises: 
Create Date: 2020-05-05 23:17:10.811340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716406e19c30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('comments_users_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'users_id')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # op.create_foreign_key('comments_users_id_fkey', 'comments', 'users', ['users_id'], ['id'])
    # ### end Alembic commands ###
