"""Ano

Revision ID: cc7acf7394c2
Revises: f585ec9cbfd5
Create Date: 2020-05-05 16:20:25.461609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7acf7394c2'
down_revision = 'f585ec9cbfd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('users_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['users_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'users_id')
    # ### end Alembic commands ###
